### ISSUE TITLE
keyError error occurs when executing train_small.sh

### ISSUE THREAD

**Issue by ngc-shj** [facebookresearch/ViewDiff#4]
Hello and thank you for the project,

I have RTX 4090.
when I execute the train_small.sh I got this error:
```log
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/train.py", line 130, in train_and_test
    train_dataloader, validation_dataloader, n_train_examples, train_dreambooth_dataloader = setup_train_val_dataloaders(
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/train_util.py", line 627, in setup_train_val_dataloaders
    dreambooth_train_dataset = CO3DDreamboothDataset(
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/data/co3d/co3d_dataset.py", line 1021, in __init__
    prompts = [image_to_prompt[os.path.splitext(os.path.basename(img))[0]] for img in images]
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/data/co3d/co3d_dataset.py", line 1021, in <listcomp>
    prompts = [image_to_prompt[os.path.splitext(os.path.basename(img))[0]] for img in images]
KeyError: **'38_1691_5067_2'
```

During the generation process of the prior preservation dataset, which is one of the data preparation steps, JPEG image files and image_to_prompt.json were generated in the following directory.
./co3d/dataset/dreambooth_prior_preservation_dataset/teddybear

- ./co3d/dataset is the root directory of the co3d dataset.

This generation process does not process all sequence data under the teddybear directory, but samples and processes 300 sequence data. image_to_prompt.json also records only 300 sequence data.

```bash
$ grep _ ./co3d/dataset/dreambooth_prior_preservation_dataset/teddybear/image_to_prompt.json | sed -e 's/_[0123]".*//' -e 's/^.*"//' | sort | uniq - c | wc -l
300
$
```

When I checked viewdiff/data/co3d/generate_co3d_dreambooth_data.py, max_sequences_per_category was 300.

```python
def main(
        prompt_file: str,
        output_path: str,
        pretrained_model_name_or_path: str = "stabilityai/stable-diffusion-2-1-base",
        device: str = "cuda",
        max_sequences_per_category: int = 300,
        max_prompts_per_sequence: int = 2,
```

However, train_small.sh trains on sequence data in the ./co3d/dataset/teddybear directory. Therefore, it appears that the keyError is occurring when trying to reference a prompt with sequence data "38_1691_5067_2" that does not exist in the image_to_prompt.json file.

```bash
$ grep 38_1691_5067_2 ./co3d/dataset/dreambooth_prior_preservation_dataset/teddybear/image_to_prompt.json
$
```

Could you please tell me how to avoid this error?

Below are all the logs output when running train_small.sh.
```log
$ export CO3DV2_DATASET_ROOT=$(pwd)/co3d/dataset
$ CUDA_VISIBLE_DEVICES=0 ./viewdiff/scripts/train_small.sh ${CO3DV2_DATASET_ROOT} "stabilityai/stable-diffusion-2-1-base" outputs/train teddybear
/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/tyro/_fields.py:826: UserWarning: Mutable type <class 'viewdiff.io_util.SaveConfig'> is used as a default value for `save`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'viewdiff.io_util.SaveConfig'> as frozen.
  warnings.warn(
03/08/2024 00:08:52 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

^[b{'thresholding', 'variance_type', 'dynamic_thresholding_ratio', 'clip_sample_range', 'sample_max_value', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
^[f{'scaling_factor', 'force_upcast'} was not found in config. Values will be initialized to default values.
^[b{'time_embedding_act_fn', 'encoder_hid_dim_type', 'cross_attention_norm', 'upcast_attention', 'time_embedding_type', 'mid_block_type', 'projection_class_embeddings_input_dim', 'resnet_time_scale_shift', 'encoder_hid_dim', 'attention_type', 'class_embeddings_concat', 'transformer_layers_per_block', 'time_embedding_dim', 'dropout', 'conv_in_kernel', 'resnet_skip_time_act', 'resnet_out_scale_factor', 'num_attention_heads', 'mid_block_only_cross_attention', 'class_embed_type', 'time_cond_proj_dim', 'addition_time_embed_dim', 'addition_embed_type', 'conv_out_kernel', 'timestep_post_act', 'addition_embed_type_num_heads'} was not found in config. Values will be initialized to default values.
03/08/2024 00:08:54 - INFO - __main__ - Initializing the StableDiffusion3D UNet from the pretrained UNet.
Load Blip Prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 913.79it/s]
  0%|                                                                                                                                                             | 0/51 [00:00<?, ?it/s]start parse dataset for category=teddybear, subset=None
03/08/2024 00:08:58 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D frames from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/frame_annotations.jgz.
03/08/2024 00:09:04 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D sequences from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/sequence_annotations.jgz.
03/08/2024 00:09:04 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D subset lists from .
03/08/2024 00:09:04 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - JsonIndexDataset #frames=246743
finish parse dataset
Category teddybear has 1236 sequences with valid pointclouds.
Category teddybear has 1236 sequences with valid recentered data.
loaded 1236/1287 valid sequences from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/custom_sequence_metadata.json
Selected 50 random sequences for category teddybear.
Parsed teddybear: using 50 sequences with 9907 frames in total.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:07<00:00,  7.10it/s]
Load Blip Prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 945.62it/s]
  0%|                                                                                                                                                             | 0/51 [00:00<?, ?it/s]start parse dataset for category=teddybear, subset=None
03/08/2024 00:09:05 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D frames from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/frame_annotations.jgz.
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D sequences from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/sequence_annotations.jgz.
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Loading Co3D subset lists from .
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - exclude_sequence: ['391_46974_93640', '373_41560_82975', '46_2596_7562', '393_47968_95188', '534_77570_150656', '444_63772_125902', '38_1675_5008', '457_64379_126856', '42_2104_6430', '387_46466_92678', '392_47802_94952', '353_37579_70740', '380_44886_89716', '598_91959_182995', '392_47443_94381', '38_1686_5058', '540_78977_153006', '46_2595_7548', '392_47834_94937', '612_97540_195796', '387_46699_92990', '394_48750_96460', '341_35542_65393', '391_46884_93389', '246_26304_51384', '394_48525_95999', '482_68882_133595', '392_47808_94891', '353_37349_70281', '387_46523_92748', '616_99318_199096', '394_48514_95986', '387_46530_92758', '575_84513_166963', '472_66680_130870', '537_78247_152118', '378_44012_87822', '392_47776_94858', '377_43705_87007', '392_47498_94471', '612_97904_197160', '604_93996_187948', '392_47757_94835', '620_101667_204118', '504_72676_141358', '620_101591_203905', '475_67237_131972', '444_63708_125709', '377_43631_86945', '579_85828_169718']
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - ... filtered 1287 -> 1237
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - Taking max 3 per sequence.
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - ... filtered 236836 -> 3711
03/08/2024 00:09:12 - INFO - pytorch3d.implicitron.dataset.json_index_dataset - JsonIndexDataset #frames=3711
finish parse dataset
Category teddybear has 1186 sequences with valid pointclouds.
Category teddybear has 1186 sequences with valid recentered data.
loaded 1186/1237 valid sequences from /mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset/teddybear/custom_sequence_metadata.json
Selected 1 random sequences for category teddybear.
Parsed teddybear: using 1 sequences with 3 frames in total.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:07<00:00,  7.14it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/train.py", line 924, in <module>
    tyro.cli(train_and_test)
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/tyro/_cli.py", line 177, in cli
    output = _cli_impl(
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/tyro/_cli.py", line 431, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/tyro/_calling.py", line 217, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/train.py", line 130, in train_and_test
    train_dataloader, validation_dataloader, n_train_examples, train_dreambooth_dataloader = setup_train_val_dataloaders(
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/train_util.py", line 627, in setup_train_val_dataloaders
    dreambooth_train_dataset = CO3DDreamboothDataset(
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/data/co3d/co3d_dataset.py", line 1021, in __init__
    prompts = [image_to_prompt[os.path.splitext(os.path.basename(img))[0]] for img in images]
  File "/mnt/data/user/venv/viewdiff/ViewDiff/viewdiff/data/co3d/co3d_dataset.py", line 1021, in <listcomp>
    prompts = [image_to_prompt[os.path.splitext(os.path.basename(img))[0]] for img in images]
KeyError: '38_1691_5067_2'
Traceback (most recent call last):
  File "/mnt/data/user/venv/viewdiff/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/mnt/data/user/venv/viewdiff/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/mnt/data/user/venv/viewdiff/bin/python3', '-m', 'viewdiff.train', '--finetune-config.io.pretrained_model_name_or_path', 'stabilityai/stable-diffusion-2-1-base', '--finetune-config.io.output_dir', 'outputs/train', '--finetune-config.io.experiment_name', 'train_teddybear', '--finetune-config.training.mixed_precision', 'no', '--finetune-config.training.dataloader_num_workers', '0', '--finetune-config.training.num_train_epochs', '1000', '--finetune-config.training.train_batch_size', '1', '--finetune-config.training.dreambooth_prior_preservation_loss_weight', '0.1', '--finetune_config.training.noise_prediction_type', 'epsilon', '--finetune_config.training.prob_images_not_noisy', '0.25', '--finetune_config.training.max_num_images_not_noisy', '2', '--finetune_config.training.validation_epochs', '1', '--finetune_config.training.dreambooth_prior_preservation_every_nth', '1', '--finetune-config.optimizer.learning_rate', '5e-5', '--finetune-config.optimizer.vol_rend_learning_rate', '1e-3', '--finetune-config.optimizer.vol_rend_adam_weight_decay', '0.0', '--finetune-config.optimizer.gradient_accumulation_steps', '1', '--finetune-config.optimizer.max_grad_norm', '5e-3', '--finetune-config.cross_frame_attention.to_k_other_frames', '2', '--finetune-config.cross_frame_attention.random_others', '--finetune-config.cross_frame_attention.with_self_attention', '--finetune-config.cross_frame_attention.use_temb_cond', '--finetune-config.cross_frame_attention.mode', 'pretrained', '--finetune-config.cross_frame_attention.n_cfa_down_blocks', '0', '--finetune-config.cross_frame_attention.n_cfa_up_blocks', '0', '--finetune-config.cross_frame_attention.unproj_reproj_mode', 'with_cfa', '--finetune-config.cross_frame_attention.num_3d_layers', '1', '--finetune-config.cross_frame_attention.dim_3d_latent', '16', '--finetune-config.cross_frame_attention.dim_3d_grid', '64', '--finetune-config.cross_frame_attention.n_novel_images', '1', '--finetune-config.cross_frame_attention.vol_rend_proj_in_mode', 'multiple', '--finetune-config.cross_frame_attention.vol_rend_proj_out_mode', 'multiple', '--finetune-config.cross_frame_attention.vol_rend_aggregator_mode', 'ibrnet', '--finetune-config.cross_frame_attention.last_layer_mode', 'no_residual_connection', '--finetune_config.cross_frame_attention.vol_rend_model_background', '--finetune_config.cross_frame_attention.vol_rend_background_grid_percentage', '0.5', '--finetune-config.model.pose_cond_mode', 'sa-ca', '--finetune-config.model.pose_cond_coord_space', 'absolute', '--finetune-config.model.pose_cond_lora_rank', '64', '--finetune-config.model.n_input_images', '3', '--dataset-config.co3d-root', '/mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset', '--dataset-config.category', 'teddybear', '--dataset-config.max_sequences', '50', '--dataset-config.batch.load_recentered', '--dataset-config.batch.use_blip_prompt', '--dataset-config.batch.crop', 'random', '--dataset-config.batch.image_width', '256', '--dataset-config.batch.image_height', '256', '--dataset-config.batch.other_selection', 'mix', '--validation-dataset-config.co3d-root', '/mnt/data/user/venv/viewdiff/ViewDiff/co3d/dataset', '--validation-dataset-config.category', 'teddybear', '--validation-dataset-config.max_sequences', '1', '--validation-dataset-config.batch.load_recentered', '--validation-dataset-config.batch.use_blip_prompt', '--validation-dataset-config.batch.crop', 'random', '--validation-dataset-config.batch.image_width', '256', '--validation-dataset-config.batch.image_height', '256', '--validation-dataset-config.dataset_args.n_frames_per_sequence', '3']' returned non-zero exit status 1.
```

**Comment by lukasHoel** [comment]
Hi, thanks for your interest in the project. It is okay that we only pick 300 sequences per category to generate the prior dataset. The dataset will only iterate over the images generated for those sequences in that case. It rather seems that the image_to_prompt.json does not contain the key '38_1691_5067_2'. Can you confirm this is the case? There should be a '38_1691_5067_2.jpg' in the same directory as the image_to_prompt.json.

**Comment by ngc-shj** [comment]
Thank you for your quick response.

The 38_1691_5067_2.jpg file exists.

```bash
 ll ./co3d/dataset/dreambooth_prior_preservation_dataset/teddybear/38_1691_5067_2.jpg 
-rw-r--r-- 1 user user 39481 Mar  7 20:55 ./co3d/dataset/dreambooth_prior_preservation_dataset/teddybear/38_1691_5067_2.jpg
```

> In case the generation script failed for some reason and you re-run it, there might be images saved without the corresponding json file being written. In this case please delete the whole directory and repeat the generation.
I got it. I'll try regenerating it!

**Comment by ngc-shj** [comment]
When I checked the create time of the JPEG files under the `dreambooth_prior_preservation_dataset/teddybear` directory, I found that the 38_1691_5067*.jpg files were unnecessary data files, so I deleted these 4 files.

Then I ran train_small.sh and the training process started without any errors. thank you.
However, the expected learning time is over 3300 hours... (Total optimization steps = 9907000)

**Comment by lukasHoel** [comment]
The training script runs longer than 60K iterations by default, but we stopped our runs after 60K iterations. This took roughly 7 days. Note that train_small also does not use the full architecture and results likely will not be consistent.

**Comment by junsukha** [comment]
@ngc-shj Hi! did you not get the OOM issue while running train_small.sh?  I even tried 32 for `dataset-config.batch.image_width` and `dataset-config.batch.image_height` in train_small.sh but still gets OOM issue. I'm using rtx 3090 ti 20GB gpu.

**Comment by ngc-shj** [comment]
Hello, @junsukha -san. 
I'm not occurred an OOM issue in my environment. I'm using RTX 4090 24GB gpu.
The following is the execution result of the nvidia-smi command while running train_small.sh. It uses 23,789BMiB of VRAM.
```bash
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.36                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090 ...    On  | 00000000:02:00.0 Off |                  N/A |
| N/A   44C    P8               7W / 150W |    571MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  | 00000000:0C:00.0 Off |                  Off |
| 33%   51C    P2              86W / 450W |  23789MiB / 24564MiB |     38%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

For more information, please see my article below (in Japanese).
- https://note.com/ngc_shj/n/n50f96770c0bf

**Comment by junsukha** [comment]
@ngc-shj oh right 24GB. I made a typo. Mine is also 24GB. Thanks for the detail. 
I just read through your wonderful article. It indeed helped me clarify the process. Thanks a lot.

**Comment by junsukha** [comment]
@ngc-shj Hi! Sorry to bother but did you not get this error while training? 
`RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered`

I had CUDA memory error when I run `./viewdiff/scripts/train_small.sh <path/to/co3d> "stabilityai/stable-diffusion-2-1-base" outputs/train <category=teddybear>`
so I tried with `CUDA_LAUNCH_BLOCKING=1` and see that Triton error.

**Comment by ngc-shj** [comment]
@junsukha san.
I did not get the error when I run `./viewdiff/scripts/train_small.sh ${CO3DV2_DATASET_ROOT} "stabilityai/stable-diffusion-2-1-base" outputs/train teddybear`
As you can see in the attached screenshot, train_small.sh is working properly.
![Screenshot 2024-03-12 11 10 19](https://github.com/facebookresearch/ViewDiff/assets/57870202/528d7b50-aed6-423d-85fe-87a78c471fe7)

**Comment by junsukha** [comment]
@ngc-shj Hi. I reinstalled the environment following the instruction on your website and now it's working. Many thanks! I see that your environment installation process has a few different steps from the author's like specifying torch cuda version. I don't exactly know what solved the issue but. Thanks.

**Comment by ngc-shj** [comment]
@junsukha san. Congrats!

**Comment by kehethan** [comment]
@ngc-shj Hi, have you finished your training?

**Comment by xdobetter** [comment]
@ngc-shj Hello, you have completed the training，Could you release the ckpt that has been trained?

**Comment by ngc-shj** [comment]
Training stopped at approximately 10.7% progress due to a runtime error in the WSL2 process. It took 10 days to reach 10.7% progress, so I think it will take 94 days to reach 100%. Windows restarts before training completes...

The most recent checkpoint saved before the runtime error is uploaded to Hugging Face.
https://huggingface.co/noguchis/viewdiff_train_teddybear

For details, please refer to section 6 of the article below. (in Japanese)
https://note.com/ngc_shj/n/n50f96770c0bf
